#!/bin/sh

# Arguments are:
# $1 - file name
# $2 - output file name
# $3 - x axis label
# $4 - y axis label
# $5 - plot title

gnuplot << EOF
set term postscript portrait
set output "$2.ps"

set xlabel "$3"
set ylabel "$4"
set title "$5"
set datafile separator ','
set size ratio 1
set key right bottom
set xtics .1
set ytics .1
set grid
set xrange [0.0:1.0]
set yrange [0.0:1.0]

plot '$1' notitle with lines lw 4 lt rgb "#555555"
set output
EOF

epstopdf $2.ps
pdfcrop $2.pdf
mv $2-crop.pdf $2.pdf



